"""
Coherence harness — runs after every training run as a mandatory gate.

Three test families:

  1. **Refusal calibration** — the architecture's distinctive feature.
     Fixed in-distribution prompts should NOT be refused; fixed OOD
     prompts (random noise, foreign script, byte-soup, emoji) MUST be
     refused. Score = mean of (in-dist accept rate, OOD reject rate).

  2. **Generation quality** — sample N continuations from in-dist
     prompts, score on lexical-fluency proxies (UTF-8 validity,
     fraction of bytes in ASCII printable range, fraction of generated
     "words" appearing in a reference wordlist).

  3. **Sample inspection** — capture a fixed exhibit set for human
     eyeball review. The honest finding from V20 was that V7's
     generation is locally fluent gibberish; we need to *see* whether
     v2.md V21-V30 changes that or just changes the BPB number.

Pass criteria:
  - refusal_calibration ≥ 0.85 (≥85% of test prompts classified correctly)
  - utf8_validity ≥ 0.95 (≥95% of generated bytes form valid UTF-8)
  - score must not regress vs the prior version's coherence record

CLI:
    python coherence.py --lib .rce_library_v22.pkl --version V22 --tag wikitext-2
    python coherence.py --lib .rce_library_v22.pkl --json   # machine-readable

Outputs:
    - JSON to coherence_<version>_<timestamp>.json
    - one row appended to BENCHMARKS.md
    - sample exhibits printed to stdout
"""
from __future__ import annotations
import argparse
import json
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent

# ---------- fixed test sets ----------
# These DON'T change between versions — that's the point. A version that
# silently regresses on a familiar prompt should fail the gate.

PROMPTS_INDIST: list[bytes] = [
    b"The quick brown fox",
    b"In the beginning was the",
    b"She walked into the room and",
    b"def factorial(n):\n    return ",
    b"Once upon a time, in a land far",
    b"The president of the United States",
    b"To be or not to be, that is",
    b"Computer science is the study of",
]

PROMPTS_OOD: list[bytes] = [
    None,  # filled in main with os.urandom(64) — fresh per run
    "Привет, как дела сегодня?".encode("utf-8"),         # Cyrillic
    "你好世界, 今天是个好日子".encode("utf-8"),            # CJK
    "🦄✨🌈🎉🚀💎🦊🐉".encode("utf-8"),                  # emoji-only
    bytes(range(0, 64)),                                   # control bytes
    b"\x00" * 64,                                          # all-zero
    bytes([0xff, 0x00] * 32),                              # alternating
]


# ---------- lexical fluency helpers ----------

def _load_wordlist() -> set[str]:
    """Try the standard Linux wordlist, fall back to a small built-in set."""
    for p in ("/usr/share/dict/words", "/usr/share/dict/american-english"):
        if os.path.exists(p):
            with open(p) as f:
                return {w.strip().lower() for w in f if 2 <= len(w.strip()) <= 24}
    return set("""
        the be to of and a in that have it for not on with he as you do at this
        but his by from they we say her she or an will my one all would there
        their what so up out if about who get which go me when make can like time
        no just him know take person into year your good some could them see other
        than then now look only come its over think also back after use two how
        our work first well way even new want because any these give day most us
        is was are were been being has had does did
        """.split())

_WORDLIST: set[str] | None = None
def wordlist() -> set[str]:
    global _WORDLIST
    if _WORDLIST is None:
        _WORDLIST = _load_wordlist()
    return _WORDLIST

_WORD_RE = re.compile(r"[a-zA-Z]{2,}")


def lexical_fluency(text: str) -> dict:
    """Return per-text fluency proxies."""
    if not text:
        return {"utf8_valid": True, "ascii_printable_frac": 0.0,
                "n_words": 0, "wordlist_hit_frac": 0.0}
    n = len(text)
    printable = sum(1 for c in text if c.isprintable() or c in "\n\t")
    words = _WORD_RE.findall(text)
    wl = wordlist()
    hits = sum(1 for w in words if w.lower() in wl)
    return {
        "utf8_valid": True,  # already decoded to str so this is by definition
        "ascii_printable_frac": round(printable / max(n, 1), 4),
        "n_words": len(words),
        "wordlist_hit_frac": round(hits / max(len(words), 1), 4),
    }


# ---------- refusal calibration ----------

def refusal_calibration(lib, ind_prompts: list[bytes],
                        ood_prompts: list[bytes],
                        tau: float = 0.5) -> dict:
    """Score how well the library distinguishes in-dist from OOD."""
    from engine import Toplevel
    if not isinstance(lib, Toplevel):
        return {"error": "library is not Toplevel-wrapped — refusal "
                "calibration requires V10's Toplevel mixture"}
    ind_correct = 0
    ind_scores = []
    for p in ind_prompts:
        r = lib.refusal_score(p)
        ind_scores.append(round(r, 4))
        if r <= tau:
            ind_correct += 1
    ood_correct = 0
    ood_scores = []
    for p in ood_prompts:
        r = lib.refusal_score(p)
        ood_scores.append(round(r, 4))
        if r > tau:
            ood_correct += 1
    in_accept = ind_correct / max(len(ind_prompts), 1)
    ood_reject = ood_correct / max(len(ood_prompts), 1)
    return {
        "tau": tau,
        "indist_accept_rate": round(in_accept, 4),
        "ood_reject_rate": round(ood_reject, 4),
        "balanced_accuracy": round((in_accept + ood_reject) / 2, 4),
        "indist_scores": ind_scores,
        "ood_scores": ood_scores,
    }


# ---------- generation quality ----------

def generation_quality(lib, prompts: list[bytes], n_samples: int = 3,
                       max_bytes: int = 60, temperature: float = 0.7) -> dict:
    """Sample and score continuations from each prompt."""
    from rce import generate
    samples = []
    fluency_acc = {"ascii_printable_frac": [], "wordlist_hit_frac": [],
                   "n_words": []}
    for p in prompts:
        for _ in range(n_samples):
            try:
                gen_b = generate(lib, p, max_bytes=max_bytes,
                                  temperature=temperature, ctx_window=16,
                                  strict_threshold=0.0, explain=False)
                gen = gen_b.decode("utf-8", errors="replace")
            except Exception as e:
                gen = f"[generate error: {e}]"
            f = lexical_fluency(gen)
            samples.append({
                "prompt": p.decode("utf-8", errors="replace"),
                "gen": gen,
                **f,
            })
            for k in fluency_acc:
                fluency_acc[k].append(f[k])
    means = {k: round(sum(v) / max(len(v), 1), 4) for k, v in fluency_acc.items()}
    return {"samples": samples, "means": means}


# ---------- top-level ----------

def coherence(lib_path: str, n_samples: int = 3,
              max_bytes: int = 60, temperature: float = 0.7,
              tau: float = 0.5, ood_random_seed: int | None = 0) -> dict:
    from engine import load_library, Toplevel
    inner = load_library(lib_path)
    if inner is None:
        return {"error": f"could not load library at {lib_path}"}
    lib = inner if isinstance(inner, Toplevel) else Toplevel(
        inner, vocab_size=256, evidence_window=32)

    # build OOD set (insert urandom)
    ood = list(PROMPTS_OOD)
    if ood_random_seed is not None:
        rs = os.urandom(64)  # session-fresh; reseed for repro if needed
    else:
        rs = os.urandom(64)
    ood[0] = rs

    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    rep: dict = {
        "ts": ts,
        "library": lib_path,
        "library_size": len(lib.programs),
        "tau": tau,
    }
    rep["refusal"] = refusal_calibration(lib, PROMPTS_INDIST, ood, tau=tau)
    rep["generation"] = generation_quality(lib, PROMPTS_INDIST,
                                            n_samples=n_samples,
                                            max_bytes=max_bytes,
                                            temperature=temperature)

    # composite gate score: refusal balanced-accuracy is the primary; if
    # refusal works, the model isn't dangerous. Generation fluency is
    # secondary — informative but not blocking, since v1.md V20 honestly
    # established that byte-level RCE generation is incoherent.
    bal = rep["refusal"].get("balanced_accuracy", 0.0)
    gen_means = rep["generation"]["means"]
    rep["gate"] = {
        "refusal_balanced_accuracy": bal,
        "refusal_ge_0_85": bal >= 0.85,
        "ascii_printable_frac": gen_means.get("ascii_printable_frac", 0.0),
        "ascii_printable_ge_0_80": gen_means.get("ascii_printable_frac", 0.0) >= 0.80,
        "PASS": bal >= 0.85 and gen_means.get("ascii_printable_frac", 0.0) >= 0.80,
    }
    return rep


def append_to_benchmarks(version: str, tag: str, rep: dict):
    bench = REPO / "BENCHMARKS.md"
    if not bench.exists():
        return
    bal = rep["refusal"]["balanced_accuracy"]
    asc = rep["generation"]["means"]["ascii_printable_frac"]
    wl = rep["generation"]["means"]["wordlist_hit_frac"]
    pass_str = "PASS" if rep["gate"]["PASS"] else "FAIL"
    note = (f"refusal {bal:.3f}, ASCII {asc:.3f}, wordlist {wl:.3f}; "
            f"library={rep['library']}; gate={pass_str}")
    row = (f"| {rep['ts'][:10]} | {version} coherence | balanced_acc | "
           f"{bal:.4f} | {tag} | {note} |\n")
    with bench.open("a") as f:
        f.write(row)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lib", required=True)
    ap.add_argument("--version", default="?", help="e.g. V22, V23")
    ap.add_argument("--tag", default="wikitext-2",
                    help="dataset tag for the BENCHMARKS.md row")
    ap.add_argument("--samples", type=int, default=3)
    ap.add_argument("--max-bytes", type=int, default=60)
    ap.add_argument("--temperature", type=float, default=0.7)
    ap.add_argument("--tau", type=float, default=0.5)
    ap.add_argument("--json", action="store_true",
                    help="emit raw JSON only")
    ap.add_argument("--no-bench-append", action="store_true",
                    help="don't append to BENCHMARKS.md (debug)")
    ap.add_argument("--out", default=None,
                    help="write the JSON report to this path")
    args = ap.parse_args()

    rep = coherence(args.lib, n_samples=args.samples,
                    max_bytes=args.max_bytes, temperature=args.temperature,
                    tau=args.tau)
    if "error" in rep:
        print(f"ERROR: {rep['error']}", file=sys.stderr)
        sys.exit(2)

    out_path = args.out or f"coherence_{args.version}_{int(time.time())}.json"
    Path(out_path).write_text(json.dumps(rep, indent=2))

    if args.json:
        print(json.dumps(rep))
        return

    print(f"=== Coherence: {args.version} ===")
    print(f"library: {args.lib} ({rep['library_size']} programs)")
    g = rep["gate"]
    pass_str = "PASS" if g["PASS"] else "FAIL"
    print(f"GATE: {pass_str}  (refusal_bal_acc={g['refusal_balanced_accuracy']:.3f} "
          f"≥0.85; ASCII printable={g['ascii_printable_frac']:.3f} ≥0.80)")
    print()
    print("Refusal calibration:")
    r = rep["refusal"]
    print(f"  in-dist accept rate: {r['indist_accept_rate']:.3f}  "
          f"(scores: {r['indist_scores']})")
    print(f"  OOD reject rate:     {r['ood_reject_rate']:.3f}  "
          f"(scores: {r['ood_scores']})")
    print()
    print("Generation samples (first per prompt):")
    seen_prompts = set()
    for s in rep["generation"]["samples"]:
        if s["prompt"] in seen_prompts:
            continue
        seen_prompts.add(s["prompt"])
        gen_one_line = s["gen"].replace("\n", " ⏎ ")[:100]
        print(f"  > {s['prompt']!r}")
        print(f"    -> {gen_one_line!r}")
    print()
    print(f"Generation means: ASCII-printable={rep['generation']['means']['ascii_printable_frac']:.3f}, "
          f"wordlist-hit={rep['generation']['means']['wordlist_hit_frac']:.3f}, "
          f"n_words avg={rep['generation']['means']['n_words']:.1f}")

    if not args.no_bench_append:
        append_to_benchmarks(args.version, args.tag, rep)
        print(f"\nappended row to BENCHMARKS.md")
    print(f"wrote {out_path}")

    sys.exit(0 if rep["gate"]["PASS"] else 1)


if __name__ == "__main__":
    main()
