"""
Programmatic inference endpoint for RCE libraries.

Used by:
  - `coherence.py` (automated post-training coherence gate)
  - the operator (one-off prompt testing)
  - `web_endpoint.py` (V18, when deployed)

Wraps `rce.generate` with a structured-output mode and Toplevel-aware
refusal handling. Auto-wraps a bare `Library` in `Toplevel` so refusal
is always a measured posterior probability (V10 invariant), never the
old V1 entropy heuristic.

Usage:
    python infer.py --lib .rce_library_v7.pkl --prompt "the cat sat on" --json
    python infer.py --lib X.pkl --prompt "..." --max-bytes 80 --tau 0.5 --temperature 0.7

Stdin mode:
    echo "hello" | python infer.py --lib X.pkl
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

from engine import load_library, Toplevel
from rce import generate, _top_voting_programs


def infer(lib_path: str, prompt: str, max_bytes: int = 80,
          temperature: float = 0.7, tau: float = 0.5,
          ctx_window: int = 16, top_voters: int = 0) -> dict:
    """One-shot inference. Always wraps the library in Toplevel for
    architectural refusal. Returns a structured dict.
    """
    inner = load_library(lib_path)
    if inner is None:
        return {"error": f"could not load library at {lib_path}"}
    if isinstance(inner, Toplevel):
        lib = inner
    else:
        lib = Toplevel(inner, vocab_size=256, evidence_window=32)

    prompt_b = (prompt + "\n").encode("utf-8", errors="replace") if not prompt.endswith("\n") else prompt.encode()
    refusal = lib.refusal_score(prompt_b)
    out: dict = {
        "library": lib_path,
        "library_size": len(lib.programs),
        "prompt": prompt,
        "prompt_bytes": len(prompt_b),
        "refusal_score": round(refusal, 6),
        "tau": tau,
        "refused": refusal > tau,
    }
    if refusal > tau:
        out["generated"] = ""
        out["stop_reason"] = "refused"
        return out

    gen_b = generate(lib, prompt_b, max_bytes=max_bytes,
                      temperature=temperature, ctx_window=ctx_window,
                      strict_threshold=0.0, explain=False)
    out["generated"] = gen_b.decode("utf-8", errors="replace")
    out["generated_bytes"] = len(gen_b)
    if gen_b and gen_b.endswith(b"\n"):
        out["stop_reason"] = "newline"
    elif len(gen_b) >= max_bytes:
        out["stop_reason"] = "max_bytes"
    else:
        out["stop_reason"] = "early"

    if top_voters > 0 and gen_b:
        first_b = gen_b[0]
        voters = _top_voting_programs(lib, prompt_b, first_b, k=top_voters)
        out["first_byte_top_voters"] = [
            {"program": n, "weight": round(w, 6)} for n, w in voters
        ]

    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lib", default=".rce_library.pkl")
    ap.add_argument("--prompt", default=None,
                    help="if omitted, read from stdin")
    ap.add_argument("--max-bytes", type=int, default=80)
    ap.add_argument("--temperature", type=float, default=0.7)
    ap.add_argument("--tau", type=float, default=0.5)
    ap.add_argument("--top-voters", type=int, default=0,
                    help="show top-k programs voting for the first generated byte")
    ap.add_argument("--json", action="store_true",
                    help="emit raw JSON (default: pretty)")
    args = ap.parse_args()

    prompt = args.prompt
    if prompt is None:
        prompt = sys.stdin.read().rstrip("\n")
    if not prompt:
        print("ERROR: empty prompt (pass --prompt or pipe via stdin)", file=sys.stderr)
        sys.exit(2)

    result = infer(args.lib, prompt,
                   max_bytes=args.max_bytes, temperature=args.temperature,
                   tau=args.tau, top_voters=args.top_voters)

    if args.json:
        print(json.dumps(result))
        return

    if "error" in result:
        print(f"ERROR: {result['error']}", file=sys.stderr)
        sys.exit(1)
    print(f"library: {result['library']} ({result['library_size']} programs)")
    print(f"prompt:  {result['prompt']!r} ({result['prompt_bytes']}B)")
    print(f"refusal: {result['refusal_score']:.4f}  (τ = {result['tau']:.2f})")
    if result["refused"]:
        print(f"REFUSED — refusal score above τ")
    else:
        print(f"reply ({result['stop_reason']}): {result['generated']!r}")
        if "first_byte_top_voters" in result:
            print("first byte top voters:")
            for v in result["first_byte_top_voters"]:
                print(f"  {v['weight']:.4f}  {v['program']}")


if __name__ == "__main__":
    main()
